name: In Good Thyme
favicon: null
layout_spectrum: 0.29862
typography_spectrum: 0.31411
title: In Good Thyme
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252037'
    - '#f3fdff'
    - '#e0ccc5'
    - '#c09079'
    - '#84494f'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.5404472511727363
  rhythmicContrast: 0.5
purpose: []
