name: In Good Thyme
favicon: null
layout_spectrum: 0.20467263367027044
typography_spectrum: 0.2816010166425258
title: In Good Thyme
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3214797433465719
  lightness: 0.220666971988976
  saturation: 0.5404472511727363
  rhythmicContrast: 0.11801191419363022
purpose: []
